#ifndef __TAINT_EXT_H__
#define __TAINT_EXT_H__

/*
 * DO NOT MODIFY. This file is automatically generated by scripts/apigen.py,
 * based on the <plugin>_int.h file in your plugin directory.
 */

#include <dlfcn.h>
#include "panda_plugin.h"

typedef void(*taint_enable_taint_t)(void);
static taint_enable_taint_t __taint_enable_taint = NULL;
static inline void taint_enable_taint(void);
static inline void taint_enable_taint(void){
    assert(__taint_enable_taint);
    return __taint_enable_taint();
}
typedef int(*taint_enabled_t)(void);
static taint_enabled_t __taint_enabled = NULL;
static inline int taint_enabled(void);
static inline int taint_enabled(void){
    assert(__taint_enabled);
    return __taint_enabled();
}
typedef void(*taint_label_ram_t)(uint64_t pa, uint32_t l);
static taint_label_ram_t __taint_label_ram = NULL;
static inline void taint_label_ram(uint64_t pa, uint32_t l);
static inline void taint_label_ram(uint64_t pa, uint32_t l){
    assert(__taint_label_ram);
    return __taint_label_ram(pa,l);
}
typedef uint32_t(*taint_query_ram_t)(uint64_t pa);
static taint_query_ram_t __taint_query_ram = NULL;
static inline uint32_t taint_query_ram(uint64_t pa);
static inline uint32_t taint_query_ram(uint64_t pa){
    assert(__taint_query_ram);
    return __taint_query_ram(pa);
}
typedef uint32_t(*taint_pick_label_t)(uint64_t pa);
static taint_pick_label_t __taint_pick_label = NULL;
static inline uint32_t taint_pick_label(uint64_t pa);
static inline uint32_t taint_pick_label(uint64_t pa){
    assert(__taint_pick_label);
    return __taint_pick_label(pa);
}
typedef uint32_t(*taint_query_reg_t)(int reg_num, int offset);
static taint_query_reg_t __taint_query_reg = NULL;
static inline uint32_t taint_query_reg(int reg_num, int offset);
static inline uint32_t taint_query_reg(int reg_num, int offset){
    assert(__taint_query_reg);
    return __taint_query_reg(reg_num,offset);
}
typedef uint32_t(*taint_query_llvm_t)(int reg_num, int offset);
static taint_query_llvm_t __taint_query_llvm = NULL;
static inline uint32_t taint_query_llvm(int reg_num, int offset);
static inline uint32_t taint_query_llvm(int reg_num, int offset){
    assert(__taint_query_llvm);
    return __taint_query_llvm(reg_num,offset);
}
typedef void(*taint_spit_reg_t)(int reg_num, int offset);
static taint_spit_reg_t __taint_spit_reg = NULL;
static inline void taint_spit_reg(int reg_num, int offset);
static inline void taint_spit_reg(int reg_num, int offset){
    assert(__taint_spit_reg);
    return __taint_spit_reg(reg_num,offset);
}
typedef void(*taint_spit_llvm_t)(int reg_num, int offset);
static taint_spit_llvm_t __taint_spit_llvm = NULL;
static inline void taint_spit_llvm(int reg_num, int offset);
static inline void taint_spit_llvm(int reg_num, int offset){
    assert(__taint_spit_llvm);
    return __taint_spit_llvm(reg_num,offset);
}
typedef void(*taint_delete_ram_t)(uint64_t pa);
static taint_delete_ram_t __taint_delete_ram = NULL;
static inline void taint_delete_ram(uint64_t pa);
static inline void taint_delete_ram(uint64_t pa){
    assert(__taint_delete_ram);
    return __taint_delete_ram(pa);
}
typedef uint32_t(*taint_occ_ram_t)(void);
static taint_occ_ram_t __taint_occ_ram = NULL;
static inline uint32_t taint_occ_ram(void);
static inline uint32_t taint_occ_ram(void){
    assert(__taint_occ_ram);
    return __taint_occ_ram();
}
typedef uint32_t(*taint_max_obs_ls_type_t)(void);
static taint_max_obs_ls_type_t __taint_max_obs_ls_type = NULL;
static inline uint32_t taint_max_obs_ls_type(void);
static inline uint32_t taint_max_obs_ls_type(void){
    assert(__taint_max_obs_ls_type);
    return __taint_max_obs_ls_type();
}
typedef uint32_t(*taint_get_ls_type_llvm_t)(int reg_num, int offset);
static taint_get_ls_type_llvm_t __taint_get_ls_type_llvm = NULL;
static inline uint32_t taint_get_ls_type_llvm(int reg_num, int offset);
static inline uint32_t taint_get_ls_type_llvm(int reg_num, int offset){
    assert(__taint_get_ls_type_llvm);
    return __taint_get_ls_type_llvm(reg_num,offset);
}
typedef void(*taint_clear_tainted_computation_happened_t)(void);
static taint_clear_tainted_computation_happened_t __taint_clear_tainted_computation_happened = NULL;
static inline void taint_clear_tainted_computation_happened(void);
static inline void taint_clear_tainted_computation_happened(void){
    assert(__taint_clear_tainted_computation_happened);
    return __taint_clear_tainted_computation_happened();
}
typedef int(*taint_tainted_computation_happened_t)(void);
static taint_tainted_computation_happened_t __taint_tainted_computation_happened = NULL;
static inline int taint_tainted_computation_happened(void);
static inline int taint_tainted_computation_happened(void){
    assert(__taint_tainted_computation_happened);
    return __taint_tainted_computation_happened();
}
typedef void(*taint_clear_taint_state_changed_t)(void);
static taint_clear_taint_state_changed_t __taint_clear_taint_state_changed = NULL;
static inline void taint_clear_taint_state_changed(void);
static inline void taint_clear_taint_state_changed(void){
    assert(__taint_clear_taint_state_changed);
    return __taint_clear_taint_state_changed();
}
typedef int(*taint_taint_state_changed_t)(void);
static taint_taint_state_changed_t __taint_taint_state_changed = NULL;
static inline int taint_taint_state_changed(void);
static inline int taint_taint_state_changed(void){
    assert(__taint_taint_state_changed);
    return __taint_taint_state_changed();
}
typedef void(*taint_clear_taint_state_read_t)(void);
static taint_clear_taint_state_read_t __taint_clear_taint_state_read = NULL;
static inline void taint_clear_taint_state_read(void);
static inline void taint_clear_taint_state_read(void){
    assert(__taint_clear_taint_state_read);
    return __taint_clear_taint_state_read();
}
typedef int(*taint_taint_state_read_t)(void);
static taint_taint_state_read_t __taint_taint_state_read = NULL;
static inline int taint_taint_state_read(void);
static inline int taint_taint_state_read(void){
    assert(__taint_taint_state_read);
    return __taint_taint_state_read();
}
typedef void(*taint_clear_shadow_memory_t)(void);
static taint_clear_shadow_memory_t __taint_clear_shadow_memory = NULL;
static inline void taint_clear_shadow_memory(void);
static inline void taint_clear_shadow_memory(void){
    assert(__taint_clear_shadow_memory);
    return __taint_clear_shadow_memory();
}
typedef void(*taint_labelset_ram_iter_t)(uint64_t pa, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static taint_labelset_ram_iter_t __taint_labelset_ram_iter = NULL;
static inline void taint_labelset_ram_iter(uint64_t pa, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static inline void taint_labelset_ram_iter(uint64_t pa, int (*app)(uint32_t el, void *stuff1), void *stuff2){
    assert(__taint_labelset_ram_iter);
    return __taint_labelset_ram_iter(pa,app,stuff2);
}
typedef void(*taint_labelset_reg_iter_t)(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static taint_labelset_reg_iter_t __taint_labelset_reg_iter = NULL;
static inline void taint_labelset_reg_iter(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static inline void taint_labelset_reg_iter(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2){
    assert(__taint_labelset_reg_iter);
    return __taint_labelset_reg_iter(reg_num,offset,app,stuff2);
}
typedef void(*taint_labelset_llvm_iter_t)(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static taint_labelset_llvm_iter_t __taint_labelset_llvm_iter = NULL;
static inline void taint_labelset_llvm_iter(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static inline void taint_labelset_llvm_iter(int reg_num, int offset, int (*app)(uint32_t el, void *stuff1), void *stuff2){
    assert(__taint_labelset_llvm_iter);
    return __taint_labelset_llvm_iter(reg_num,offset,app,stuff2);
}
typedef void(*taint_labelset_iter_t)(LabelSetP ls, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static taint_labelset_iter_t __taint_labelset_iter = NULL;
static inline void taint_labelset_iter(LabelSetP ls, int (*app)(uint32_t el, void *stuff1), void *stuff2);
static inline void taint_labelset_iter(LabelSetP ls, int (*app)(uint32_t el, void *stuff1), void *stuff2){
    assert(__taint_labelset_iter);
    return __taint_labelset_iter(ls,app,stuff2);
}
#define API_PLUGIN_NAME "taint"
#define IMPORT_PPP(module, func_name) { \
 __##func_name = (func_name##_t) dlsym(module, #func_name); \
 char *err = dlerror(); \
 if (err) { \
    printf("Couldn't find %s function in library %s.\n", #func_name, API_PLUGIN_NAME); \
    printf("Error: %s\n", err); \
    return false; \
 } \
}
static inline bool init_taint_api(void);static inline bool init_taint_api(void){
    void *module = panda_get_plugin_by_name("panda_" API_PLUGIN_NAME ".so");
    if (!module) {
        printf("In trying to add plugin, couldn't load %s plugin\n", API_PLUGIN_NAME);
        return false;
    }
    dlerror();
IMPORT_PPP(module, taint_enable_taint)
IMPORT_PPP(module, taint_enabled)
IMPORT_PPP(module, taint_label_ram)
IMPORT_PPP(module, taint_query_ram)
IMPORT_PPP(module, taint_pick_label)
IMPORT_PPP(module, taint_query_reg)
IMPORT_PPP(module, taint_query_llvm)
IMPORT_PPP(module, taint_spit_reg)
IMPORT_PPP(module, taint_spit_llvm)
IMPORT_PPP(module, taint_delete_ram)
IMPORT_PPP(module, taint_occ_ram)
IMPORT_PPP(module, taint_max_obs_ls_type)
IMPORT_PPP(module, taint_get_ls_type_llvm)
IMPORT_PPP(module, taint_clear_tainted_computation_happened)
IMPORT_PPP(module, taint_tainted_computation_happened)
IMPORT_PPP(module, taint_clear_taint_state_changed)
IMPORT_PPP(module, taint_taint_state_changed)
IMPORT_PPP(module, taint_clear_taint_state_read)
IMPORT_PPP(module, taint_taint_state_read)
IMPORT_PPP(module, taint_clear_shadow_memory)
IMPORT_PPP(module, taint_labelset_ram_iter)
IMPORT_PPP(module, taint_labelset_reg_iter)
IMPORT_PPP(module, taint_labelset_llvm_iter)
IMPORT_PPP(module, taint_labelset_iter)
return true;
}

#undef API_PLUGIN_NAME
#undef IMPORT_PPP

#endif
