#ifndef __SAMPLE_EXT_H__
#define __SAMPLE_EXT_H__

/*
 * DO NOT MODIFY. This file is automatically generated by scripts/apigen.py,
 * based on the <plugin>_int.h file in your plugin directory.
 */

#include <dlfcn.h>
#include "panda_plugin.h"

typedef int(*sample_function_t)(CPUState *env);
static sample_function_t __sample_function = NULL;
static inline int sample_function(CPUState *env);
static inline int sample_function(CPUState *env){
    assert(__sample_function);
    return __sample_function(env);
}
typedef int(*other_sample_function_t)(CPUState *env, int foo);
static other_sample_function_t __other_sample_function = NULL;
static inline int other_sample_function(CPUState *env, int foo);
static inline int other_sample_function(CPUState *env, int foo){
    assert(__other_sample_function);
    return __other_sample_function(env,foo);
}
#define API_PLUGIN_NAME "sample"
#define IMPORT_PPP(module, func_name) { \
 __##func_name = (func_name##_t) dlsym(module, #func_name); \
 char *err = dlerror(); \
 if (err) { \
    printf("Couldn't find %s function in library %s.\n", #func_name, API_PLUGIN_NAME); \
    printf("Error: %s\n", err); \
    return false; \
 } \
}
static inline bool init_sample_api(void);static inline bool init_sample_api(void){
    void *module = panda_get_plugin_by_name("panda_" API_PLUGIN_NAME ".so");
    if (!module) {
        printf("In trying to add plugin, couldn't load %s plugin\n", API_PLUGIN_NAME);
        return false;
    }
    dlerror();
IMPORT_PPP(module, sample_function)
IMPORT_PPP(module, other_sample_function)
return true;
}

#undef API_PLUGIN_NAME
#undef IMPORT_PPP

#endif
